services:
  mongo:
    image: mongo:latest
    expose:
      - "27017:27017"
  server:
    image: sandwich.azurecr.io/eteedir-server:latest
    build: ./server
    ports:
      - "80:8080"
    environment:
      - ADDRESS=0.0.0.0:80
      - MONGODB=mongo:27017
